nmap <leader>tq <Plug>(maque-query)
map <silent> <f2> <Plug>(save-all)<Plug>(auto-maque)
map <silent> <f6> <Plug>(save-all)<Plug>(maque)
nmap <silent> <f3> <Plug>(maque-parse)
nmap <silent> <f9> <Plug>(maque-toggle-tmux)
nmap <silent> <f10> <Plug>(maque-tmux-kill)
nmap <silent> <leader>mc <Plug>(maque-tmux-close)

nmap <leader><f1> <plug>(maque-unite-command)
nmap <leader><f2> <plug>(maque-unite-tmux-pane)
