let g:htf_project_name = 'ribosome-root'
let g:haskell_compile_project = 'ribosome'
let g:myo_haskell_compile_project = 'ribosome'
let g:myo_haskell_test_project = 'ribosome-root'
let haskell_project_lib_prefix = 'modules/core/lib'
