let g:surround_105 = "IO[\r]"
let g:surround_101 = "Either[String, \r]"
let g:surround_102 = "Future[\r]"
let g:surround_73 = "${\r}"
let g:surround_108 = "List[\r]"
let g:surround_111 = "Option[\r]"
let g:surround_115 = "Stream[IO, \r]"
